// Minimal wallet metadata resolver extracted from n8n "wallet map" node
// Keep keys in lowercase for case-insensitive lookup

function toLower(value) {
    return (value || '').toString().trim().toLowerCase();
}

// Complete wallet map from n8n example
const WALLET_MAP = {
    "dymsqudnqjyydvq86xmzavru9t7xwfqewh6gpqw9tpnf": { name: "unprofitable", telegram: null, twitter: "https://x.com/exitliquid1ty" },
    "5rkpdk4jnvaumgzev2zu8vjggmtthddtrsd5o9dhgzhd": { name: "Dave Portnoy", telegram: null, twitter: "https://x.com/stoolpresidente" },
    "amofvgj59dgf5p85pofip83pk7nzqrqrmszvv5rrfvtf": { name: "7xNickk", telegram: null, twitter: "https://x.com/7xNickk" },
    "gwofjfjutuswq2ewtz4p2sznoq9xylrf8t4q5kbtgz1r": { name: "Levis", telegram: "https://t.me/LevisAlpha", twitter: "https://x.com/LevisNFT" },
    "6m5sw6eapahncxnzapi1zvjnrb9rzhq3bj7fd84x9raf": { name: "ShockedJS", telegram: "https://t.me/shockedjstrading", twitter: "https://x.com/ShockedJS" },
    "4yzpszpxddjnf3unjkctdwesz2fl5mok7e5xqadnqry8": { name: "xunle", telegram: null, twitter: "https://x.com/xunle111" },
    "4wptqa7bb4irdrphgnpjihgcxkh8t43gljmn5pbevfqw": { name: "Oura", telegram: "https://t.me/OuraEmergencyCalls", twitter: "https://x.com/Oura456" },
    "ckpfgv2wv1vwdwjtxioegb8jhzqfs3evzez3qcetu7xd": { name: "Lynk", telegram: "https://t.me/lynkscabal", twitter: "https://x.com/lynk0x" },
    "4uteaz9tmz1j5bnkgglvqaelvchjwlzgo7hxar2kaiyu": { name: "Monarch", telegram: "https://t.me/MonarchJournal", twitter: "https://x.com/MonarchBTC" },
    "3pz59yenxdacjaka3sahzjbcger4rgyi4v6bppurmsgj": { name: "Kadenox", telegram: null, twitter: "https://x.com/kadenox" },
    "g3g1ckqkwsvevurzdnmazdbv7yahmntjhjbvrtikzygk": { name: "Insyder", telegram: null, twitter: "https://x.com/insydercrypto" },
    "gjyhzlozaxzhzgpvf3v1wsygunogsq55n6hn6nhv7w8b": { name: "LilMoonLambo", telegram: null, twitter: "https://x.com/LilMoonLambo" },
    "64ymed9xtaknjghtxgrg6jcnzmbc9fsvcmgkl54pfike": { name: "Phineas.SOL", telegram: "https://t.me/PhineasCabal", twitter: "https://x.com/Phineas_Sol" },
    "grd2umbfebjqkfpdqvmmynq5eyrl9sadwjj9ffmyeadn": { name: "Solstice", telegram: "https://t.me/solsticesmoonshots", twitter: "https://x.com/The__Solstice" },
    "ha1l7ghqfypsrdfbi3tckkcvedecbvyqbsqcencrwpub": { name: "Hail", telegram: null, twitter: "https://x.com/ignHail" },
    "d1h83uesw5nxy5okxh7vbfv4jrnqak5mm1tm3jaj3m5t": { name: "Jeets", telegram: null, twitter: "https://x.com/ieatjeets" },
    "34zeh778zl8ctklwxxerlx5znuu6mufyx9cwrs8kucmw": { name: "Groovy", telegram: null, twitter: "https://x.com/0xGroovy" },
    "8oqomhfbqnrspn7qtnaq2apthre4q94klstwaafqvrgs": { name: "big bags bobby", telegram: null, twitter: "https://x.com/bigbagsbobby" },
    "j23qr98gjgjjqkq9cbenyrhhbmkavxttjnnxku597wsa": { name: "gr3g", telegram: null, twitter: "https://x.com/gr3gor14n" },
    "j6tdxvarvpbdpxtatu8ejbtso1pucykgkvtmkuuy8iea": { name: "Pain", telegram: "https://t.me/PainCrypto69", twitter: "https://x.com/PainCrypt0" },
    "7dp8dmrka5rmqti4zeedjdayaqyvfspkcxmjekjucqcu": { name: "JB", telegram: null, twitter: "https://x.com/Jeetburner" },
    "3bljrcxwgtr7wrshj3hl25u3rjwr5ud98wmcczqqk4ei": { name: "Sebastian", telegram: null, twitter: "https://x.com/Saint_pablo123" },
    "enjoy9bmqgaud9akc4hpubhbyvdzwp7jqppkukevdywm": { name: "Enjooyer", telegram: null, twitter: "https://x.com/0xEnjooyer" },
    "gp9pytwgybx3q3tc5dmrkeuq8dr15upvvn3z9fkbemph": { name: "Sweep", telegram: "https://t.me/jsdao", twitter: "https://x.com/0xSweep" },
    "9x5n5i1mugtjggphqf1kjdt8r4kd8tf3s62ttbxkzfha": { name: "dingaling", telegram: null, twitter: "https://x.com/dingalingts" },
    "9bkaujdfyuybknbzwv4mnnyfevkhhvjulb7cl4gfqalt": { name: "goob", telegram: "https://t.me/goobscall", twitter: "https://x.com/ifullclipp" },
    "b3wagqzizu2hka5pucj6rrdhwsx3q6wfttnki9pjwzmh": { name: "xander", telegram: "https://t.me/xanderstrenches", twitter: "https://x.com/xandereef" },
    "dzaa55hwxgv5hstwatejgxzz1dhhejvpb7yr762urxam": { name: "ozark", telegram: null, twitter: "https://x.com/ohzarke" },
    "8hkzkqcgzwxnvrz1xavmbuzcafqo5xfjh17vm2j2hte1": { name: "Exy", telegram: null, twitter: "https://x.com/eth_exy" },
    "5m8acgkexg1ojkdtmh3smqhtihtghymsszc6w8i7qw3y": { name: "Unipcs (aka 'Bonk Guy')", telegram: null, twitter: "https://x.com/theunipcs" },
    "5pxkp8rpg7xhekff7urj25i4p5zxvk8hrquadkytu5k7": { name: "Leens", telegram: "https://t.me/leenscooks", twitter: "https://x.com/leensx100" },
    "bteqnydtkydasxqnrm8byaudpk3cpq1fsxmtaf1hfaom": { name: "FINN", telegram: null, twitter: "https://x.com/finnbags" },
    "gv8yfcu9wesgpn6fcgkg9nirqcyf9wvzaqnq1djrsfce": { name: "Lectron", telegram: null, twitter: "https://x.com/LectronNFT" },
    "winkacdsxstg19hjgx1pwdgpd8f2zpiqqajyabkgxlu": { name: "Don", telegram: "https://t.me/dontrenches", twitter: "https://x.com/doncaarbon" },
    "atmewwb6y6kndgu2dpjt5dsar84bfcbnxliw2dyyfm8p": { name: "Sizeab1e", telegram: "https://t.me/thetradingcorps", twitter: "https://x.com/sizeab1e" },
    "gitjplmyngdkzyxyc2mbfbwss1zt3nbcjjtagsgb3ajv": { name: "Flames", telegram: null, twitter: "https://x.com/FlamesOnSol" },
    "aelb2rpvwrqkzj87peifdreiexjxacqn17c8apqs1fhx": { name: "oscar", telegram: null, twitter: "https://x.com/oscarexitliq" },
    "bu8izsgvs5dwuy3giedjusdayeme7lthh4x7trgtnmxa": { name: "printer", telegram: null, twitter: "https://x.com/prxnterr" },
    "4ud45ngbqtbptqpyovtclcccs1evh1zlsvvlmmdqn2jw": { name: "Bronsi", telegram: "https://t.me/Bronsisinsiderinfo", twitter: "https://x.com/Bronsicooks" },
    "9pgkiusnhxme5p4dogwzt9i6of7xympnnj5tgbrzvqk6": { name: "staticc", telegram: null, twitter: "https://x.com/staticctrades" },
    "fsambd6jm6szzqadsjec1pax3ottaiy9htx1uyzvoxqj": { name: "Zil", telegram: "https://t.me/zilcalls", twitter: "https://x.com/zilxbt" },
    "86aejexyjenngcp7gravcxtdicf5agwgoerbxfig1edd": { name: "Publix", telegram: null, twitter: "https://x.com/Publixplayz" },
    "alaug4fweydgsxd5hen6kvuwscdui2fynsnqm1ci31we": { name: "Thurston (zapped arc)", telegram: null, twitter: "https://x.com/itsthurstxn" },
    "dnsh1ufjdxmze6t6gv9qk5sofm7hsm5trnxvuwvgo8zj": { name: "Hash (Poop Arc)", telegram: "https://t.me/HashTrades", twitter: "https://x.com/Hashbergers" },
    "3tsrae3pdx4ejacxbiwi9ny8mnychekjv5dbawazfksq": { name: "guappy", telegram: null, twitter: "https://x.com/guappy_eth" },
    "an68xcxjvfxc9nrwjnxgsfy55dyfvkjfgtpt8akgj2de": { name: "bihoz", telegram: null, twitter: "https://x.com/bihozNFTs" },
    "fpd6n8gfoznxyan6qqnh4tfqdv9vzegcv5w4h2yl8k4x": { name: "Hesi", telegram: null, twitter: "https://x.com/hesikillaz" },
    "gnrmkzcxyynisusjduwwpjzhed3latjciikvusgrshec": { name: "Giann", telegram: null, twitter: "https://x.com/Giann2K" },
    "eqaxqkt3n981qbmdsugnzagk5s26zuwadrhhbcgn87zd": { name: "jamessmith", telegram: null, twitter: "https://x.com/luckedhub" },
    "avjetg2ecykxyeqdrqxvaaazbjftjyusmtr4wlhkoeqn": { name: "Putrick", telegram: "https://t.me/cryptoputro", twitter: "https://x.com/Putrickk" },
    "4ddrfidhpmx55i4spssxvzs9zaklb8qr45nky9er9nnh": { name: "Mr. Frog", telegram: null, twitter: "https://x.com/TheMisterFrog" },
    "fc3nyvqdufvfrgxirjeqgst1jdjsebez6a9kobffp7c4": { name: "psykГё", telegram: null, twitter: "https://x.com/psykogem" },
    "3i8akm4xfsx9wkfb5bq61fmiykekqefqvdmeyu6psek9": { name: "MoneyMaykah", telegram: null, twitter: "https://x.com/moneymaykah_" },
    "5rqecwjzdhkxrmbwjsq32raocgypawdhi3ztimwucrwo": { name: "EvansOfWeb", telegram: null, twitter: "https://x.com/EvansOfWeb3" },
    "a5uxhmjtvybd1aj4bfuaekujppjawncrlsrjhjayvjh4": { name: "Owl", telegram: null, twitter: "https://x.com/OwlFN_" },
    "dxwdrwxqxdavzquh3yvcvbq75nuf16fttq4q88okn5mc": { name: "Sebi", telegram: "https://t.me/launchlog", twitter: "https://x.com/limpcritisism" },
    "gah2tkptu7hspbckbmanpcdbssarfeswoscffrvf7oha": { name: "gambles.sol", telegram: "https://t.me/launchlog", twitter: "https://x.com/mastern0de3" },
    "4ntyfqqrzvhwstmjzot26h9xtl7aswgtxpcpcxikax9a": { name: "Inside Calls", telegram: "http://t.me/callsfromwithin", twitter: "https://x.com/insidecalls" },
    "4nvnc7ddeqkklm4sr9kgk3t1of6f8g66kt64voc95lyh": { name: "M A M B A рџ§І", telegram: null, twitter: "https://x.com/mambacrypto__" },
    "fkzekjmlgbxc8nusqq2u53rmdh3jhfazr2psdoudyvfr": { name: "lucas", telegram: null, twitter: "https://x.com/driz1x_" },
    "37y6bz7axphhrzmhgmqgrxv8jmuhqcs2ffhrpzkuert2": { name: "Laanie", telegram: "https://t.me/laaniecalls", twitter: "https://x.com/cryptolaanie" },
    "3wz6mfb1druvtozvcptvv1qahq5fkj3qpzr4db45g6jk": { name: "B*", telegram: null, twitter: "https://x.com/BeezyScores" },
    "6hcx7fvmzerpw3d7xhfsxyw2cuepfgsmmouzxsinlj1u": { name: "Ataberk рџ§™вЂЌв™‚пёЏ", telegram: null, twitter: "https://x.com/ataberk" },
    "cxnf4tt7qfz3kznwn3yve5mkaryxgoay2edx3qt8e99m": { name: "trav рџЋ’", telegram: "https://t.me/travjournal", twitter: "https://x.com/travonchain" },
    "75oeqxzc569dy1g6uwexvipz4pm8zkhkdsk2ft9dug5i": { name: "boogie", telegram: null, twitter: "https://x.com/boogiepnl" },
    "fcbc2do6qcqhhmdcmp7eqbdb6r8hcwxjojkjqmghoz3": { name: "Monki", telegram: "http://t.me/cryptomonki", twitter: "https://x.com/m0nkicrypto" },
    "aen6lkc7sgvptyjmd5cu9b9xvjl7m9pnvaip2znjc4gz": { name: "Aroa", telegram: "https://t.me/AroasJournal", twitter: "https://x.com/AroaOnSol" },
    "4vw54bmaogerv3vpkwyfet5yf8dtlcrezdszx4rw9ud9": { name: "decu", telegram: "https://t.me/DecusCalls", twitter: "https://x.com/notdecu" },
    "4bdkaxn8g6ka4gytqqwk4g4dzrutx2vqh9gcxdbrefuk": { name: "Jijo", telegram: "https://t.me/jijosjournal", twitter: "https://x.com/jijo_exe" },
    "9fnz4mjpumnjqtf6yedbl1d4sshvh7ua8zrhhr5k138r": { name: "Danny", telegram: null, twitter: "https://x.com/0xSevere" },
    "8rvasdkeacejekizmug9k8v1y8mw6gqqimobd89uy7qr": { name: "Casino", telegram: "https://t.me/casino_calls", twitter: "https://x.com/casino616" },
    "831yhv67qpkqlbjjbmw2xodueefhgux8rnurj9imeoes": { name: "Trey", telegram: "https://t.me/treystele", twitter: "https://x.com/treysocial" },
    "bcagckxemchukrhed6fkfa1uiwdtcmcxmsqaheliupjd": { name: "dv", telegram: null, twitter: "https://x.com/vibed333" },
    "as7hjl7dzzvbrbad3wcun47robib2kmakrxmvjhksmb5": { name: "Otta", telegram: "https://t.me/ottabag", twitter: "https://x.com/ottabag" },
    "dn7pylsgyqhxwvplh8tjm2zojjhmssngvrvkmwvpredr": { name: "Fabix", telegram: "https://t.me/FabixAlpha", twitter: "https://x.com/Fabix_Sol" },
    "722txm5ub5uug2tc43ukhxq7pbyz75ptokeajv9x5vtx": { name: "sp", telegram: null, twitter: "https://x.com/SolanaPlays" },
    "4cxnf2z85uiz5cykspmeulq1yufatpkatmx4j4dbzqj2": { name: "WaiterG", telegram: "https://t.me/Waitercooks", twitter: "https://x.com/Waiter1x" },
    "dsqrytuh1r37asycvf1kdx4cnnz5dkefmnxvgt4nftpe": { name: "Classic", telegram: "https://t.me/mrclassiccalls", twitter: "https://x.com/simplyclassic69" },
    "di75xbvug3u1qcmzci3ncz8rjfmj7tsnyeofdemjs4ow": { name: "NвЂ™o", telegram: null, twitter: null },
    "fngkt9n6a9tut52pxqe6j9zsgejpj7mhm9c1ufrbpdd2": { name: "Rektober", telegram: "https://t.me/RektNFA", twitter: "https://x.com/rektober" },
    "btmbmpkonbnlf9xn552guqq528kkxcsnbnnbre3oaqtr": { name: "Letterbomb", telegram: null, twitter: "https://x.com/ihateoop" },
    "4zdcphjrsn4e9gmfp8jjfsaexhgja2ten4jmxfeentyt": { name: "Robo", telegram: "https://t.me/robogems", twitter: "https://x.com/roboPBOC" },
    "f5jwyuidltialya54d88ybpxgesa6nkhzwy4sn4bmyjt": { name: "mercy", telegram: null, twitter: "https://x.com/mercularx" },
    "aj6mgexek7fxmekkkpmaljcdxvstxyokynv9uvfdrtvo": { name: "Tim", telegram: null, twitter: "https://x.com/timmpix1" },
    "balxyjxzatanfm7cc5afhwbpiwnsb71thcnofdltwapk": { name: "peely рџЌЊ", telegram: "https://t.me/peelystree", twitter: "https://x.com/0xpeely" },
    "8rrmajxywand4zeskfpqusye35dtzaytuwykz3ewczqx": { name: "Te'", telegram: "https://t.me/trenchwithte", twitter: "https://x.com/TeTheGamer" },
    "8fani7xawzvc17sci13dhi2neyntqgjzyrbxwgymefj1": { name: "Midjet", telegram: null, twitter: "https://x.com/MidjetV2" },
    "faicxnv5fvqtfbpn4zccs71xcfgeyxbsgbqldydjzjke": { name: "radiance", telegram: null, twitter: "https://x.com/radiancebrr" },
    "buhkhhm3j4vif71pmtd23ywxphf35lunc2qclavuxcdw": { name: "Saif", telegram: null, twitter: "https://x.com/degensaif" },
    "2w3zdw2e1kjytm2phtkgh78l8djmrc6fub9uhwknigts": { name: "Yokai Ryujin", telegram: null, twitter: "https://x.com/YokaiCapital" },
    "ekddjxzj39bjkr47niargjdkfvxiiv9wnj5xbtehpexp": { name: "YOUNIZ", telegram: null, twitter: "https://x.com/YOUNIZ_XLZ" },
    "ebjxstfqbbnxvfexouqgfuxqfmaehu6kfbxrzqkgbjru": { name: "Zinc", telegram: "https://t.me/zincalpha", twitter: "https://x.com/zinceth" },
    "5b79fmkcfertiwm7ehszsfiksc7m7n1bgv9ylxpp9q2x": { name: "bandit", telegram: null, twitter: "https://x.com/bandeeeez" },
    "ccucjek5p6dloh2yntjizxyhanstxaqagvxhp1cyjf7w": { name: "el charto", telegram: "https://t.me/ChartoCartel", twitter: "https://x.com/elchartox" },
    "aelamjzxerzt4drbwvwvcxpvyo8p94xu5vrg41ezpfe3": { name: "^1s1mple", telegram: null, twitter: "https://x.com/s1mple_s1mple" },
    "hlv6ycepgjqv9pcksvjpem8esyultyh9hjhn9ctqsek1": { name: "Lyxe", telegram: "https://t.me/+yFy-8j3uwBBjMzhl", twitter: "https://x.com/cryptolyxe" },
    "bar5csytpwonpwhujixx7zphxkucifzzjbp9unxzxjph": { name: "Jack DuvalрџЊЉ", telegram: null, twitter: "https://x.com/jackduvalstocks" },
    "4qvu8f17s9ox2tjolcaqyv1p56gdytyf7qfm3knwewjf": { name: "waste management", telegram: "https://t.me/managingwaste", twitter: "https://x.com/wastemanagem3nt" },
    "fqexjvzpt7bqcznvs82q46lfpuevg7yodikpugpjaicb": { name: "Padly", telegram: null, twitter: "https://x.com/Padly1k" },
    "bcnqspeta1tkgednyeebrpkmwfrjdcjmqckzmmtedarc": { name: "TheDefiApe", telegram: "https://t.me/DEFIAPEALERTS", twitter: "https://x.com/TheDefiApe" },
    "exkcuoazjcgcvju3cvnol8vvrdestwkx3ubj6rqxwqm4": { name: "DJ.ОЈn", telegram: "http://t.me/djeninfo", twitter: "https://x.com/thisisdjen" },
    "cxe1d5zfifk4a4uzohqack7sfqd84xjcky1qtjnz3bge": { name: "BagCalls", telegram: "https://t.me/bagcalls", twitter: "https://x.com/BagCalls" },
    "7abz8qefzthpkovmdsmqkm64dzwn5wrtu7letd2shkq6": { name: "Red", telegram: "https://t.me/yvlred", twitter: "https://x.com/redwithbag" },
    "4xhghy4r41xnegehpksc725azjy6tr5e92xnjs4odbpr": { name: "bruce", telegram: null, twitter: "https://x.com/onchainscammer" },
    "2wn4rnemb9c9ouc7vtb4cbxbyiy7qtmcvwuxkkq2d47t": { name: "shah", telegram: "https://t.me/shahlito", twitter: "https://x.com/shahh" },
    "7sds3pjt2mswkq7zo4ftucn9gjdtuw4jaacpa65bsehs": { name: "Insentos", telegram: "https://t.me/insentos", twitter: "https://x.com/insentos" },
    "eavboapxfcyanjonwdkxtbpvt57nhxgu5i6m9m6zs2kk": { name: "danny", telegram: null, twitter: "https://x.com/insentos" },
    "zyncuicspp5zexdpvprgx8twz1axtaqaeqttvz45art": { name: "zync (й”Њд»”)", telegram: null, twitter: "https://x.com/cladzsol" },
    "qnghurucgjpxjdsnv74ushercbm3crxrsnp8d6z34hh": { name: "Dan", telegram: null, twitter: "https://x.com/zyncxbt" },
    "hkft55p3phrwhxotfeuvkkee4ab26xz1bk6umxv88pwz": { name: "Terp", telegram: null, twitter: "https://x.com/100xDan" },
    "gknnf4nwkr61b1qkbftele6tvzfhyrac2lbvkonyckb": { name: "Prada", telegram: null, twitter: "https://x.com/OnlyTerp" },
    "g6fuxjmkpjzcy1rveae6qm7wy5u3vzgkdjmn1vpadizc": { name: "clukz", telegram: null, twitter: "https://x.com/clukzSOL" },
    "71pcu3e4jp5rdboy6wjteqzxkknxlye1byg5btal9utq": { name: "Ramset вњџ", telegram: null, twitter: "https://x.com/Ramsetx" },
    "5xvkfrue4zzeoz3aqbqffmb5asscy5nsyc6vwtqwniid": { name: "IМ·М‘НЊН†М¤М Н•lМґМЅМ‹МіМєМ¦yМµМЉН†Мє", telegram: null, twitter: "https://x.com/retardily" },
    "fi2hrxexy6tjnkcbptqpo6izzx9suvbb9mdw6d29ngcn": { name: "quant", telegram: null, twitter: "https://x.com/retardily" },
    "9eftigvxhunjqzxiv3bq7wd2v7ufvdrqbrrndepr8ptk": { name: "Seee", telegram: null, twitter: "https://x.com/tstar_frr1" },
    "fajy79ncahjn7kmqzsowwrk3mhxtnc3bphkx3hxuv8y6": { name: "Advyth", telegram: null, twitter: "https://x.com/Advyth" },
    "bqvz7fq1wsqmstmy3umdpepptm1sdcbcx9sp7o6kprmb": { name: "Limfork.eth", telegram: "https://t.me/limforkdiary", twitter: "https://x.com/Limfork" },
    "kjxb1ot9nkcvq1zd27vznsbappct82dpvnxrcwxftvy": { name: "i gamble your yearly salary", telegram: null, twitter: "https://x.com/letsfknbetonit" },
    "ejtqrptbcmevstbkpnjsh23nfucmhghustyshugvqzp2": { name: "Zef", telegram: "https://t.me/SefaPVP", twitter: "https://x.com/zefwashere" },
    "winriha1p9n1qs22qbjkbmvf4sfphtevcnqcwmdsc2t": { name: "mog", telegram: null, twitter: "https://x.com/10piecedawg" },
    "ynrdbimhtefz66v7brtmbaptyrexwxrerrzw8uqkgfj": { name: "Jdn", telegram: "http://t.me/jaden", twitter: "https://x.com/JadenOnChain" },
    "b3beyovnkbo4wf1ufrfgfpveyehjfyjpmebciz7kpnos": { name: "Spuno", telegram: null, twitter: "https://x.com/spunosounds" },
    "gfxqespe3zuwg8jhat6cg8eujdtvx751enp9eqqmhzph": { name: "Meechie", telegram: "https://t.co/zb0ZJIEhEm", twitter: "https://x.com/973Meech" },
    "9iaawvbesfg35pswd4pahwt8fynqe9xyurdwm872duqy": { name: "fa1r", telegram: null, twitter: "https://x.com/fa1rtrade" },
    "fzvqszj8jjr6wmgqbuhzx2xh1kkrfxrrrpv6wcbbzmnd": { name: "bust", telegram: "https://t.me/dustsdungeon", twitter: "https://x.com/IAmAboutToBust" },
    "fbvuu5qvd9jsu9jp3kdwecpzivzhloqbq1ppcaabd6fb": { name: "profitier", telegram: null, twitter: "https://x.com/profitierr" },
    "axwssg5njqodkofclv6ypjl4r5usvysyt9q7yvwjegah": { name: "Sue", telegram: "https://t.me/sues_degenjournal", twitter: "https://x.com/sue_xbt" },
    "2puuzytokrgdv2yzl6m5pjb1jyohe367yu1sdq7ac3ea": { name: "Log", telegram: null, twitter: "https://x.com/Log100x" },
    "m7kaas3kd8fhlnciosjcosuvdrez6fdnbvm6htnyuf7": { name: "Ferb", telegram: null, twitter: "https://x.com/ferbsol" },
    "5wcc13mxoyqe6qh2ihh5gfknojoj7y13zpx9k4nxtuo3": { name: "Dolo", telegram: "https://t.me/DolosTradingDojo", twitter: "https://x.com/doloxbt" },
    "j6p2ms1gjygk9hod8vkuefcuwqmwfawqfjyjx7uc8p6b": { name: "dean bulla", telegram: null, twitter: "https://x.com/deanbulla" },
    "htvlccfehifb7g4j42jdn53zd7sqrielf5whzjznvwmm": { name: "Polly", telegram: "https://t.me/WildyJournals", twitter: "https://x.com/0xsushi" },
    "ebk5atdfrcuki27dhzaw5yysfreezvvu8xebhmxqoex6": { name: "Sully", telegram: "https://t.me/kitchenofsully", twitter: "https://x.com/sullyfromDeets" },
    "7tirxpm4wwbmrmyzmywrae6jves3gdbnyxgrreou6rla": { name: "Qtdegen", telegram: null, twitter: "https://x.com/qtdegen" },
    "uxuumeyx2pzphmgz2w3q8mysvexcaqumtvefqp2etvm": { name: "Pandora", telegram: null, twitter: "https://x.com/pandoraflips" },
    "jdd3hy3gqn2v982mi1zqhnquw1gfv2ul6g76stojcjpn": { name: "West", telegram: null, twitter: "https://x.com/ratwizardx" },
    "g5nxexufmfv74dsnsrsatqcw32f34xunbeq3pfds7w5e": { name: "Profit", telegram: "https://t.me/ProfitsPlays", twitter: "https://x.com/FlippingProfits" },
    "9eypamyqvxauwfxd2uqhvg8vpkks33ydxvdvwmrxruih": { name: "Connor", telegram: null, twitter: "https://x.com/Connoreo_" },
    "215nhcahjqqggwpqsjq7zr26etbjjtvdw74nlzwegqjp": { name: "OGAntD", telegram: null, twitter: "https://x.com/0GAntD" },
    "brt5kyq125u6narkfknibnhak6x7mvczsq3lfqcb3sqg": { name: "zoru", telegram: null, twitter: "https://x.com/zoruuuuu" },
    "qp3q8d4wwsgbqktfya9dr6cad7dqobuxpjmftk48rwu": { name: "kitty", telegram: "https://t.me/KittysKasino", twitter: "https://x.com/0xkitty69" },
    "9jyqfilnruggwnn4eqwbnfxwpblm9hra4hv59ytyavvz": { name: "Nach", telegram: "https://t.me/NarrativeNach", twitter: "https://x.com/NachSOL" },
    "719sfkujimthumtt2u39vmgn612bzyccwbm5pe8sqfyz": { name: "Fashr", telegram: null, twitter: "https://x.com/FASHRCrypto" },
    "av3xwhj5esolzag6pr7lkbrgglrtaykxomdd5kbhl9yq": { name: "Heyitsyolo", telegram: null, twitter: "https://x.com/Heyitsyolotv" },
    "4bdn33fa7llzquuxuflsxtpwgaunmbcreqhfh9mxuixe": { name: "wuzie", telegram: "https://t.me/wuziemakesmoney", twitter: "https://x.com/crypt0wu" },
    "akht8ebjqfslmhnr7wdr53ymwjmb9urzbzywy7fajkeh": { name: "s0ber", telegram: null, twitter: "https://x.com/whaIecrypto" },
    "hq5ttulwwmdjgvzqukgujhqogz5ufscyyhpp756uvyae": { name: "Scharo", telegram: "http://t.me/ScharoCooks", twitter: "https://x.com/XScharo" },
    "cvniezb8hofushckqu8irj6t2fky7vjzpsckofmzk5mb": { name: "Dali", telegram: null, twitter: "https://x.com/SolanaDali" },
    "sadnbe1cknmdqdsa4npb3tfl62t14uao2msuqflvzlt": { name: "Ethan Prosper", telegram: null, twitter: "https://x.com/pr6spr" },
    "6hjetmbdhbuk3mluainxappbpwzdgybhgts2tqdausx2": { name: "LJC", telegram: "https://t.me/LJCcabals", twitter: "https://x.com/OnlyLJC" },
    "9v9xsxxu2pi4cdkthtyl1rg417uga48r2vccp4l1pe9r": { name: "fl0wjoe", telegram: null, twitter: "https://x.com/fl0wjoe" },
    "9wagwcs6hvtmhaaxbjube7akmxeg9nzedcvxhn8bydug": { name: "killz", telegram: null, twitter: "https://x.com/KillzzSol" },
    "hbcxe8ywqjwnk3f3fx4oohgm87fzupyd4ydszqxgkwft": { name: "Stacker вњќпёЏ", telegram: null, twitter: "https://x.com/Stackeronsol" },
    "a9atubuxovy547n6hubcq9ozm36ltjx9kvn4nzxffxvp": { name: "Burixx рџ‡®рџ‡№", telegram: "https://t.me/BurixxDegenCorner", twitter: "https://x.com/Burix_sol" },
    "4s2wzrla35fb58bzy1i4cn3woywjeuyrgyhntkfst23z": { name: "jester", telegram: null, twitter: "https://x.com/thejester" },
    "7gi4h4wugm2n3rrwa6bijsqpjv7smardawti2txdl9zm": { name: "Ricco рџҐЂ", telegram: null, twitter: "https://x.com/RiccoRosas" },
    "4esy8hqb4ak65difrshjwwhksgc8skmnzyusm993gk2w": { name: "prosciutto", telegram: "http://t.me/prosciuttosol", twitter: "https://x.com/prosciuttosol" },
    "au1guwfcadx7jmzhsg6ghgugviyjrnpfl1vbdqnvlk4i": { name: "Hugo Fartingale", telegram: null, twitter: "https://x.com/HugoMartingale" },
    "69z4qtgq5dbrtjvnqzx2h8jzhnsv5ugadotewwkum2js": { name: "King", telegram: null, twitter: "https://x.com/thekryptoking_" },
    "g3gzwqryknmyfkycyfrcntguxdyue2wiykkzpizn4wss": { name: "Goyim", telegram: null, twitter: "https://x.com/bnbquant" },
    "b9oksevkrnttvfadyauoh7ovmoyvbbfuf4nkyqc4kk2d": { name: "Fozzy", telegram: null, twitter: "https://x.com/fozzycapone" },
    "bjnueazdxlpwhnpmvzrb5b8dttbhdmxtg1zarpcj1yyj": { name: "Affu (aura farming)", telegram: "https://t.me/affucalls", twitter: "https://x.com/lethal_affu" },
    "bnahnx13rlru9zxuwngbd7vvv1pgqxb11q7qetyupdwf": { name: "rayan", telegram: "https://t.me/rayanhouse", twitter: "https://x.com/traderayann" },
    "gmdxqhhxqfzeberqqpft9xkznvgfkx6bcut65mxqznbj": { name: "рџ‡©рџ‡ґ Jerry", telegram: null, twitter: "https://x.com/0xJrmm" },
    "7vbtpiiejkwrbrghjfuz6o5fwuhpftamy8jghnqwhnnn": { name: "Brox", telegram: "https://t.me/broxcalls", twitter: "https://x.com/ohbrox" },
    "8dej9xeuvxsjwicypta9mhsu2rn2pdx37kwzkdkexhu6": { name: "Cooker", telegram: "https://t.me/CookersCooks", twitter: "https://x.com/CookerFlips" },
    "8eiozubsrjfknefcshkdbwa8mkpmxmbvqcfargslviue": { name: "0xJumpman", telegram: null, twitter: "https://x.com/0xjumpman" },
    "f1wt79jkw3bkbdufcbrkko15ghzncejvnjxqpicfpurm": { name: "flock (6'3)", telegram: null, twitter: "https://x.com/melgibsonfan99" },
    "ctuzwarj8a13m3hdjaxvslkqjufmfkqwzfxjpcq4mimx": { name: "Chris в•пёЏ", telegram: null, twitter: "https://x.com/ChrisCoffeeEth" },
    "b8kdogv1a39gpvpsipjpdugfff8nx6evexrmvdeixb64": { name: "Jakey", telegram: null, twitter: "https://x.com/SolJakey" },
    "kilogfwuxp7nby7xi6r9t7u8erqyrdazg6wbjvue49u": { name: "kilo", telegram: null, twitter: "https://x.com/kilorippy" },
    "41uh7g1dxyayxdtjbiychcgbniv9wx57b7hu7rxmx1gg": { name: "Lowskii (believes)", telegram: "http://t.me/lowskiicooks", twitter: "https://x.com/Lowskii_gg" },
    "65paneg8m7mcvoasvf2kbrdu21akxdassb9g3njcsque": { name: "Pullup рџ—ЎпёЏрџ§ЈвњЁ", telegram: null, twitter: "https://x.com/pullupso" },
    "fqojc24nun3x6omqc2ypbhmth7rfanks6dvwsjocmaiv": { name: "CoCo", telegram: "https://t.me/cococabin", twitter: "https://x.com/CoCoCookerr" },
    "89hbgwdulwoxcofwpmn1eif9wedpgkndeypjzz72mkdi": { name: "AlxCooks", telegram: null, twitter: "https://x.com/AlxCooks_off" },
    "abcx4xbm7dj3i9p29i6su8wlmiw4fwy5tiwb9d6ubbce": { name: "404Flipped", telegram: null, twitter: "https://x.com/404flipped" },
    "avazvhlr2pcwpdf8bxy4rvxnhyrbytychkcb5z5qnxym": { name: "Ansem", telegram: null, twitter: "https://x.com/blknoiz06" },
    "2kv8x2a9bxnbm8nklc6bbtx2z13gfnrl4orotmujrva9": { name: "Gh0stee", telegram: null, twitter: "https://x.com/4GH0STEE" },
    "2t5ngddidkvhjqg8ahdi74ucfwgp25pyfmrzxbacunbh": { name: "Idontpaytaxes", telegram: null, twitter: "https://x.com/untaxxable" },
    "eddcrfddeiidxdntrp59abh4dxhfnu48zpmpyisdmja7": { name: "Mezoteric", telegram: null, twitter: "https://x.com/mezoteric" },
    "duqabfqdc9eebulva7ttdzyxe8vk8ct5dzr4xcf7docy": { name: "orangie", telegram: null, twitter: "https://x.com/orangie" },
    "4jfpysoutrafbfdjp9qpa1j5pxjmmjyowhiftpolpq6x": { name: "MERK", telegram: "http://t.me/MerkTradingCalls", twitter: "https://x.com/MerkTrading" },
    "gl8vlakj5aeankvnd4gqakjxlqazjenbnxuqbdo8fwqg": { name: "polar", telegram: null, twitter: "https://x.com/polarsterrr" },
    "7bstkewcspg6nzsbxucxv89yuulosexnjdx2wqflhwz4": { name: "BIGWARZ", telegram: null, twitter: "https://x.com/bigwarzeth" },
    "dedew3smpu2dcfxecgj2yppmx9h3bnmdjau4ctn2bqdq": { name: "King Solomon", telegram: "https://t.me/alwaysgems", twitter: "https://x.com/0xsolomon" },
    "jbtjakwqyr471nmehqlsualeznz4yx2wy9jyotvegnem": { name: "Fawcette", telegram: null, twitter: "https://x.com/0xsolomon" },
    "bjxjrq566xt66pcxcmcmlpsunxyuppnbdjgp56s7fmda": { name: "h14", telegram: null, twitter: "https://x.com/H14onX" },
    "us74riglopmkdi169rpub4vsf6t9pqchtpg5jwzvhvp": { name: "para", telegram: null, twitter: "https://x.com/paradilf" },
    "huk3kumlslbzser2n7mxmmpaje1ekcr8djs6ddom3m8f": { name: "Little Mustacho рџђ•", telegram: "https://t.me/LittleMustachoCalls", twitter: "https://x.com/littlemustacho" },
    "dugezklzp8ul2aqmhthouibec7wsbpnikfjlttk1qhjx": { name: "Eddy рџ’№рџ§І", telegram: "https://t.me/MrEduTrades", twitter: "https://x.com/EddyMetaX" },
    "5d3jqcuuvsuhyzkhdp78ffqc7wogrzzpttec1x9vnkue": { name: "Legend", telegram: null, twitter: "https://x.com/legend_calls" },
    "egjcs3ulucu5jn83xumirpr6171zvn5i6wc12sdivgx3": { name: "Leck", telegram: "https://t.me/LeckSol", twitter: "https://x.com/LeckSol" },
    "98t65wcmejonldtjszbhgzex75qre8qaanxokv4yw3mp": { name: "Tuults", telegram: "https://t.me/tuults1coma05x", twitter: "https://x.com/tuults69" },
    "bwqpafcn5fp5ok2x5w69wspbsgirxuppuyx8zgnm7xeq": { name: "SatsBuyer", telegram: "https://t.me/+QuSpUmbxgtszOGI1", twitter: "https://x.com/Satsbuyer" },
    "dnfuf1l62wwyw3pnakvkyggfzvvhj4yr52jsmdtyebhm": { name: "Gake", telegram: "https://t.me/GakesBakes", twitter: "https://x.com/Ga__ke" },
    "7puhvakdz96s9p5fat2eede8eykxy9iuhvalamfqfcyj": { name: "jitter", telegram: null, twitter: "https://x.com/jitterxyz" },
    "8zfzhusrudpuar7j6fzwyf3vknx4cvw3dfhjerqhc7zd": { name: "Pow", telegram: "https://t.me/PowsGemCalls", twitter: "https://x.com/traderpow" },
    "egny4zmqxuaqodclw366jjd2ecki6pvmmf74mksxmfqw": { name: "Eric Cryptoman", telegram: "https://t.me/Erics_Calls", twitter: "https://x.com/EricCryptoman" },
    "6qs6job349h7zu1z9xrgpgmsmpbyldqb2wtaecy4lysh": { name: "Chefin", telegram: "https://t.me/ChefinAlpha", twitter: "https://x.com/Chefin100x" },
    "14hdbsrjcjkgwcxdbxv8pgrgfalraqdbq2mcwsa46q5x": { name: "0xMistBlade", telegram: null, twitter: "https://x.com/0xMistBlade" },
    "2bu3nazgra2gg2mpzwwxpa8x4ccralgrf6ty1fkfjpx2": { name: "Issa", telegram: "https://t.me/issasthoughts", twitter: "https://x.com/issathecooker" },
    "f2suerm4mviwj2hzkxk2nuzbc6xe883cfwudcpz6cywm": { name: "Earl", telegram: null, twitter: "https://x.com/earlTrades" },
    "ca4kexltgjwbcswivjtmfbghq8pfsgrwfxlrrctirzu5": { name: "old", telegram: null, twitter: "https://x.com/old" },
    "dpnvrta3erfkzx4f8pi2cvykdjjjonxyy5qgoytawd26": { name: "Gorilla Capital", telegram: "https://t.me/gorillacapitalcooks", twitter: "https://x.com/gorillacapsol" },
    "525lueqayzjuecoiisfwy6nyh4mtvmf4x9jsqi6efxjt": { name: "Joji", telegram: "https://t.me/jojiinnercircle", twitter: "https://x.com/metaversejoji" },
    "c4bwycclsbehgzzvupfzjgvjk2nqpn8em9wtzurh4gzw": { name: "Obijai", telegram: null, twitter: "https://x.com/Obijai" },
    "9vk7pkbz9kfjmzapznyjgedyz8qokmqtnyyyi2aehnmt": { name: "Xelf", telegram: "https://t.me/xelfalpha", twitter: "https://x.com/xelf_sol" },
    "f5tjpysiujmdvqmzhnpp85rc1verdgv5fr5p2vdvm429": { name: "Zyaf", telegram: "https://t.me/zyafgambles", twitter: "https://x.com/0xZyaf" },
    "gm7hrz2bdq33ezmtl6kgidswzxmwgz6qbuugkb5h8nvn": { name: "Beaver", telegram: null, twitter: "https://x.com/0xZyaf" },
    "hwrnkq7rptkhvx9wyhsc1zvfhtgjpqa5tyztgtbvfxe": { name: "Jay", telegram: null, twitter: "https://x.com/beaverd" },
    "dbmrhnbssvx8f6nyvaaaiugdwo1aygawiy3jfncvxysc": { name: "Bobby", telegram: null, twitter: "https://x.com/BitBoyJay" },
    "gvqtcyiqly3tknpgzpa81rsckycam1zltqsybdndjmkf": { name: "GVQ", telegram: null, twitter: "https://x.com/GVQ_xx" },
    "frbunvgxync1efngpn7ad3f14akktjvc6zsmtvj2dycs": { name: "Henn", telegram: null, twitter: "https://x.com/henn100x" },
    "hrcpndvdgbpbfxkxer6pw3qecfaqqnnjb6ajnfwgteng": { name: "0xWinged", telegram: null, twitter: "https://x.com/0xExorcized" },
    "3h65mmpzksokkyepejnwu2yk2iyt5ozdnitgy5ctaxoe": { name: "Jidn", telegram: "https://t.me/JidnLosesMoney", twitter: "https://x.com/jidn_w" },
    "eanb5151l8ejp3sm6halgyv3snk6oqc8ackgweg9t5j": { name: "Jordan", telegram: null, twitter: "https://x.com/176Dan" },
    "j2b5fnm2daauaga4eaegwqfoyan6b5ferga5sjtqoagm": { name: "Dan176", telegram: "https://t.me/DansCall", twitter: "https://x.com/176Dan" },
    "5ayjw1vndgtho2chipbvmugqtux1fcvvklnechqkqrw8": { name: "Bolivian", telegram: "http://t.me/boliviantrades", twitter: "https://x.com/_bolivian" },
    "9yyya3f5ejolnbnkw6z4bzvyqytmxzdcpu5d6yyr4jql": { name: "Loopierr", telegram: "https://t.me/loopierrsjourney", twitter: "https://x.com/Loopierr" },
    "bxnim7pqt9ld3b2hc8it3ma5bswoe9crrtksus15slwn": { name: "Absol", telegram: "https://t.me/absolcalls", twitter: "https://x.com/absolquant" },
    "mw4pzb45ishmnjgklpjvjkbzvs5nxztj8udyug4gtsm": { name: "Dex", telegram: null, twitter: "https://x.com/igndex" },
    "6lchayryteyjlehhzo4hdemgnwu2aia8cm8vhr9wn6n7": { name: "Assasin.eth", telegram: null, twitter: "https://x.com/assasin_eth" },
    "3kebnkw7cpdsklrfimealyzjgz4wdisrvmon4rd1ypzv": { name: "Bastille", telegram: null, twitter: "https://x.com/BastilleBtc" },
    "gja1hebxgnqbhbifh9uqauzxsb53to5rhdrzmkxhsu65": { name: "Latuche", telegram: null, twitter: "https://x.com/Latuche95" },
    "3mpypxb7viyedlv4sifmesvy5w5zkknwgmb4tpcz77qe": { name: "Carti The Menace", telegram: null, twitter: "https://x.com/CartiTheMenace" },
    "agnd5wthmubyk3kjjqpdqfm3tbwcupttkwbfwvuwiclu": { name: "Angi", telegram: "https://t.me/angiscalls", twitter: "https://x.com/angitradez" },
    "ehg5yku2szbtvut87rusvxargp3hleye1fxasdfumyaf": { name: "TIL", telegram: null, twitter: "https://x.com/tilcrypto" },
    "3nvc8csrebqfexzjupkfwzmpk7xydqcnoxmfbjxiizvx": { name: "Cented", telegram: null, twitter: "https://x.com/valueandtime" },
    "cyae1vxvbrahnpwkqm5vsdcvys2qmnht2ufrkjhga54o": { name: "Cented", telegram: null, twitter: "https://x.com/Cented7" },
    "7i7vhev87bs135duojvke9c7abentawa5ydfwcwc8iy2": { name: "ChartFu", telegram: null, twitter: "https://x.com/ChartFuMonkey" },
    "8mava9kdt3nw4q5hynam1x5lbr8pqrvdc1w8nmvk88d5": { name: "Daumen", telegram: null, twitter: "https://x.com/daumenxyz" },
    "9vwutdtbs66hwkecmxalfpkky4q5rse8dsfjfdxj5yfa": { name: "Dutch", telegram: null, twitter: "https://x.com/0xDutch_" },
    "dfmxre4ckmvogblrpigxmibvttqduzjdxojwzjcxxhzj": { name: "Euris", telegram: null, twitter: "https://x.com/Euris_JT" },
    "hus9erdrdqpqqepbmfgjutndte6ez8es62a25rihsk9u": { name: "Hustler", telegram: "https://t.me/hustlersalpha", twitter: "https://x.com/JoeVargas" },
    "btf4a2exgk9bcvdnzy65b9duzxgmqb4wevkvtmfqsadd": { name: null, telegram: null, twitter: null },
    "6s8gezkxyufzy9jptynanbcztmb87wjt1qx3c6elajkc": { name: "Nyhrox", telegram: null, twitter: "https://x.com/Kevsznx" },
    "99i9uva7q56by22ajkkuftztgtep5yctvgsrg9j4pdyq": { name: "Zrool", telegram: null, twitter: "https://x.com/nyhrox" },
    "egzjrcbcdripc1bw52tcvgdnkdbqwczqb": { name: "Rev", telegram: null, twitter: "https://x.com/solrevv" },
    "ae3tjdeyudwbm8zoub3ico563gmbq26jtckfvjcvzbsa": { name: "Roxo", telegram: null, twitter: "https://x.com/ignRoxo" },
    "b7fdzjnb7dlyh1a37tkefss1rrsz5c7mygtrrmawzbqa": { name: "Lucas", telegram: "https://t.me/frontruncalls", twitter: "https://x.com/CryDevil23" },
    "j4ryypexhwymvynzvwrstyasvphv4sxk6kqnggvbdvc4": { name: "RUSKY рџЄ¬вљЎпёЏ", telegram: "https://t.me/cryptorusky", twitter: "https://x.com/CryDevil23" },
    "dxudj2dq5odnqgzvuocaewc1eyc78q8vfmvtppvtrrnh": { name: "storm", telegram: "http://t.me/stormcooks", twitter: "https://x.com/stormtradez" },
    "5vg7he5hibvsaw86wfiup6jw7vwkmuanp6p93mvcdpju": { name: "blixze в™±", telegram: null, twitter: "https://x.com/blixze" },
    "72yie4crbv2uhxrgryks4gatgt2avbacfl4hncfqlqsm": { name: "kyz", telegram: null, twitter: "https://x.com/kyzenill" },
    "fwamtvsmajxyze4nt5ooldg6ahhux3st3nz89ogsgu59": { name: "Hueno", telegram: "https://t.me/HuenosTaxEvaders", twitter: "https://x.com/HuenoZ" },
    "6dwbgyf7jblumsmeagn9zmcv2skf6s6ugaqtbkdzjtw4": { name: "Noah", telegram: "https://t.me/noahhcalls", twitter: "https://x.com/Noahhcalls" },
    "87rrdssfitjky4mgara4g5vq31hmr7mxsmhzeaj5aaxj": { name: "Dior", telegram: null, twitter: "https://x.com/Dior100x" },
    "2w14ahxd3xbfwjchq4k5nlxmguwwcttutuhdhezeuvp3": { name: "Veloce", telegram: null, twitter: "https://x.com/VeloceSVJ" },
    "c9hzbnbc36aq44sdkucwueuxhftckglqmo7l5vnsuxtw": { name: "Frags", telegram: null, twitter: "https://x.com/cryptofrags" },
    "fpx2bava7j2c7nz6wpopl9f5kdakjxlb38phnzmoxcra": { name: "Achi", telegram: null, twitter: "https://x.com/cryptofrags" },
    "astawujuqias3afqmm3xzxrjhkkznxtw4vyagqfqv6jl": { name: "asta", telegram: null, twitter: "https://x.com/AchillesXBT" },
    "2yjbcb9g8weprpvbct31o8jeed6l3abgycjt5qkjmymv": { name: "Al4n", telegram: null, twitter: "https://x.com/Al4neu" },
    "9fehwfjgbynfcrrhkesjnq6znhjc5aaq7tiki1rcvsnh": { name: "fomo рџ§ ", telegram: null, twitter: "https://x.com/fomomofosol" },
    "dv32u9mvsxgvnshf7xm7afumoprifqxzuzejfmfmyszy": { name: "deecayz вЊђв—Ё-в—Ё", telegram: "https://t.me/summerprinter", twitter: "https://x.com/deecayz" },
    "7k7itu678xaaucupq2f3c2dcjirrjby4hmtw1dx6hil6": { name: "DRT рџђ‚", telegram: null, twitter: "https://x.com/pepeDRT" },
    "zhynxqk3mnsmws3yxsvpmy5kua1n2wuacjgyudrahkl": { name: "zhynx", telegram: null, twitter: "https://x.com/onlyzhynx" },
    "bjyxvf81mgahqgahdtuegzxzp7bzra4p5dg67y4e3bxz": { name: "0xBossman", telegram: "http://t.me/BossmanCallsOfficial", twitter: "https://x.com/0xBossman" },
    "2fbbtmk9mn3zxkz3anqoagnrqny2svraaazq2sfsbftm": { name: "iconXBT", telegram: null, twitter: "https://x.com/0xBossman" },
    "gberknpahpnbgmeugwqvjgbdbj6ccjkpgz34fqegmtgu": { name: "Scrim", telegram: null, twitter: "https://x.com/iconXBT" },
    "3l8raxlkvwkz4cghivavrtq19741fadglk5dgjrfc1fw": { name: "Inquixit", telegram: null, twitter: "https://x.com/inquixit" },
    "hfx9e1vvwyommihutmsaq2grkj2n4sncuwhumr83llss": { name: "yassir", telegram: null, twitter: "https://x.com/yassirwtf" },
    "9bs2xgzynpdmfbpn3hqx8nkwltopdwgrmhrbzruwbypd": { name: "woopigрџ§™рџЏ»вЂЌв™‚пёЏ", telegram: "https://t.me/woopigschannel", twitter: "https://x.com/crypto_woopig" },
    "aamnono3tpezkct7ah9pulfz4d59muehqhjjqpx16ccg": { name: "sarah milady", telegram: "https://t.me/Solana100xhunt", twitter: "https://x.com/saracrypto_eth" },
    "7w7f4p284zjhv3zotjcumanszssrhqktpxgbjfq8gdzq": { name: "eq", telegram: "https://t.me/marcellcooks", twitter: "https://x.com/404flipped" },
    "atfruwvymh61w2ab6azxuyxsafiiug1rql6iv3vi9q2b": { name: "Marcell", telegram: "https://t.me/marcellcooks", twitter: "https://x.com/MarcellxMarcell" },
    "dkgvpfttzmjqzxdavdwtxwsvkajibjzjnn2fa99dycik": { name: "Rрџ’«WDY", telegram: "https://t.me/CryptoUpdates", twitter: "https://x.com/RowdyCrypto" },
    "2fg5qd1ed7rznncsvnhmxfm5hqngwttg8p7kq6f3rx6f": { name: "Cupsey", telegram: null, twitter: "https://x.com/Cupseyy" },
    "ftg1gqw7vpm4kdu1lpm7jjnizbgpdrdy2pitkw6my27j": { name: "7", telegram: null, twitter: "https://x.com/Soloxbt" },
    "274vmggkuyqp8fxvb8n3cr9zey3sym6lgeaxm6js2nd6": { name: "Maurits", telegram: "https://t.me/mauritsfree", twitter: "https://x.com/mauritsneo" },
    "eesx4wehrqhebmbyfvfqa633v2p4c558bhh2ed7zgzh": { name: "Dolo рџҐ·", telegram: "https://t.me/DolosColdCalls", twitter: "https://x.com/Dolonomix" },
    "4uct4g7yhh4xxfmfnfkudenwgrrngoz9ay1xfxfughqg": { name: "chingchongslayer", telegram: null, twitter: "https://x.com/chingchong6257" },
    "fsg3bapmrtdsrpaivbgjsfncca8cpfkutk8vlwxkhphp": { name: "Reljoo", telegram: null, twitter: "https://x.com/Reljoooo" },
    "3pcmvz1dwkbqnjbgbeg3fyctht1aktpgqyb96jgu6os1": { name: "Fizzwick Bramblewhistle", telegram: null, twitter: "https://x.com/fizzwickBW" },
    "fkl99xvbparncptjxnldqffcg3cvcr7njcgkmgdpffw3": { name: "Nilsрџ€", telegram: "https://t.me/nilshouse", twitter: "https://x.com/nilsthedegen" },
    "hygra7nfunhgz7hspix4n7evmmu5t5btuueoxwfctkjd": { name: "zurh", telegram: null, twitter: "https://x.com/zurhxbt" },
    "j15mcwmu8eesvaifttym8tecoxxf82aluh6fgtdy5q1g": { name: "Fwasty", telegram: null, twitter: "https://x.com/Fwasty" },
    "9ha3rjrznyvznkoj5xyov3zbjthrc8e8wndjn48fqydd": { name: "Dragon", telegram: null, twitter: "https://x.com/DragonOnSol" },
    "9thzox5ygnsgpbajcf4lgqc1wlxofkmqit4xwbhhrnqe": { name: "Dedmeow5", telegram: "https://t.me/nicotinelounge", twitter: "https://x.com/dedmeow5" },
    "14k7d9ha5zff4emqd6qtpbqm25criea7zqtjm3fhypgz": { name: "Charlie", telegram: null, twitter: "https://x.com/Charlduyomeme" },
    "8tp391adbkkpqs7ekncefnj8cmek6jatee2lfkdj2prp": { name: "JinMu", telegram: "https://t.me/jinmucall", twitter: "https://x.com/LongzuAlpha" },
    "3uz65g8e463ma5fxcsu1rtuywrtrrlrzyskktehhj7qn": { name: "Felix", telegram: "https://t.me/felixtradez", twitter: "https://x.com/Felixonchain" },
    "ez2jp3rwxubatx7xwihgawvgtpfdzjosg8topqbxfajn": { name: "Keano", telegram: null, twitter: "https://x.com/nftkeano" },
    "5snnkuwkutzkdc1efnyqz3xhpnocrq1d1dfhcnhmv7gn": { name: "cryptovillain26", telegram: null, twitter: "https://x.com/cryptovillain26" },
    "nichfngmijnufzzvgyhes6zkzgepcfkunkeziyrjkbb": { name: "nich", telegram: null, twitter: "https://x.com/nichxbt" },
    "catk62cyqdfxth3rsrbs1ibcyzbeovc2kxpxeaxeg3nb": { name: "Coasty", telegram: null, twitter: "https://x.com/coasty_sol" },
    "aa5lycwalujagelyqe7y2jlzx3qetynzqyvw2blpwc2q": { name: "Grimace", telegram: null, twitter: "https://x.com/Nuotrix" },
    "ea4mxkyf8c2nzy8fw2acjpuarmou271krccayplzmbjr": { name: ".exe", telegram: null, twitter: "https://x.com/naughtygrimace" },
    "42nsek51owym3uciurvferqk77yhxzyjblrgkdzjpv2g": { name: ".exe", telegram: "https://t.me/exejournal", twitter: "https://x.com/itoptick" },
    "f72vy99ihqsywqedcfz7igkxa5me6vn2zqvsvutpw6ql": { name: "Jalen", telegram: null, twitter: "https://x.com/RipJalens" },
    "5b52w1zw9tuwuduuep5j7hxz5acgfrugox6yoaudvyxg": { name: "Yenni", telegram: null, twitter: "https://x.com/Yennii56" },
    "9nl6thsiaoydnm7xf8hebmoqeg172wmg7ikypygvjfgo": { name: "Scooter", telegram: null, twitter: "https://x.com/imperooterxbt" },
    "9k18mstuaxmsfsboa9qdtqwtnyhtzqdgehukrtvrgh6g": { name: "Sabby", telegram: null, twitter: "https://x.com/sabby_eth" },
    "aprnqn2hkbcn7w2wwit2fekvukjp9lugryae1a9hdz1": { name: "S", telegram: null, twitter: "https://x.com/runitbackghost" },
    "4be9cvxqhw6byiraxw9q3xu1yctmwal5z8nx4hr3ha7t": { name: "Mitch", telegram: "https://t.me/whimsicalclown", twitter: "https://x.com/idrawline" },
    "5t9xbnuddgtgpjaptx6hkd7sdrjbvtks8mhq6qvbo8qz": { name: "Smokez", telegram: null, twitter: "https://x.com/SmokezXBT" },
    "bpwsae36ty6ofz7f5mjsftgqzi3ttm1asatjmvub91tt": { name: "Rizz", telegram: null, twitter: "https://x.com/sollrizz" },
    "dyan4xpakn5mhixkrb7dgq4jadnx6xygu8l5b3wghbrt": { name: "The Doc", telegram: "https://t.me/+9OnlKXERe9hkODBh", twitter: "https://x.com/KayTheDoc" },
    "boyhjokntk3pjkav8qfojeonspwmwmfqocztwdd1bcgg": { name: "Betman", telegram: null, twitter: "https://x.com/ImTheBetman" },
    "ehqd8q5ran8v7y7egxym3tp4kpqmtvwqtzjsspp3upg3": { name: "Collectible", telegram: null, twitter: "https://x.com/collectible" },
    "bhrekfkpqgatds8vb1uflkupjg6scidtjhacwfug2atx": { name: "Risk", telegram: null, twitter: "https://x.com/risk100x" },
    "xxprspae1ajq4tjp78ts3x1aqnwjvq4vvb1swg4hhqh": { name: "aloh", telegram: "https://t.me/alohcooks", twitter: "https://x.com/alohquant" },
    "3ztwp8petwtfluf1rguqguxwyehcxfmoelxghqzkqnaj": { name: "cxltures", telegram: null, twitter: "https://x.com/cxlturesvz" },
    "2x4h5y9c4fy6pf3wpq8q4gmvlcwvfrrwdv2bdr8aawqv": { name: "Orange", telegram: null, twitter: "https://x.com/OrangeSBS" },
    "8yydicbpd4nm8txrqevdpa4ag8jys8r7z1kksgpl4pwh": { name: "Michi", telegram: null, twitter: "https://x.com/michibets" },
    "e7gozeiapnhpjsds52amhhn2xcaqlza7wprhyr6c8o4s": { name: "evening", telegram: null, twitter: "https://x.com/eveningbtc" },
    "4s8ybct6hhi7nr1nnkf6jf856lln8jjfzd1a8nf5uuha": { name: "shaka", telegram: "https://t.me/shakasisland", twitter: "https://x.com/solanashaka" },
    "aeejupcigr3ycoukth1g58o4lysueyzrxtfmfmc2kjmx": { name: "Damian Prosalendis", telegram: "http://t.me/prosacalls", twitter: "https://x.com/DamianProsa" },
    "fuzzuht5qkncddmxlnkein7dh1cmspwpscp55iexz85t": { name: "Fuzz", telegram: null, twitter: "https://x.com/slfuzz" },
    "3h9lvharjboz2ypesgfbvd1zuercgwfp4aeyhohsfsec": { name: "JADAWGS", telegram: null, twitter: "https://x.com/10xJDOG" },
    "b57chv7sa7ftorfskwrwi5qpjjun6cv4cumqczgw4vy2": { name: null, telegram: "https://t.me/fullstackhitler", twitter: null },
    "agqjivjr1dsv73tvuvdtqawogzmthzvymvxjgwg2fylm": { name: "nob mini", telegram: null, twitter: "https://x.com/noobmini_" },
  };
  

function resolveWalletMeta(walletAddress) {
    const key = toLower(walletAddress);
    const meta = WALLET_MAP[key] || null;
    return {
        wallet_name: meta ? meta.name : null,
        wallet_telegram: meta ? meta.telegram : null,
        wallet_twitter: meta ? meta.twitter : null,
    };
}

module.exports = { resolveWalletMeta };


